parameters:
    - name: agentPool
      type: string
    - name: solutionName
      type: string
    - name: solutionDirectory
      type: string
    - name: developmentFrameworkVersion
      type: string
    - name: buildConfiguration
      type: string
    - name: sonarcloud
      type: object

stages:
  - stage: build
    jobs:
      - job: Build_DotNet_Package_Job
        displayName: Build .Net Package
        ${{ if ne(parameters.agentPool, 'null')}}:
          pool:
            vmImage: ${{ parameters.agentPool }}
        steps:

        - template: ../steps/dotnet-framework.yaml
          parameters: 
            developmentFrameworkVersion: ${{ parameters.developmentFrameworkVersion }}
        - ${{ if and(ne(contains(variables['Build.SourceBranchName'],'refs/tags/v')), eq(variables['Build.Reason'], 'IndividualCI')) }}:
          - template: ../steps/dotnet-sonarcloud-prepare.yaml
            parameters: 
              serviceConnection: ${{ parameters.sonarcloud.serviceConnection }}
              organization: ${{ parameters.sonarcloud.organization }}
              projectKey: ${{ parameters.sonarcloud.projectKey }}
              projectName: ${{ parameters.sonarcloud.projectName }}
        
        - template: ../steps/dotnet-build.yaml
          parameters: 
            solutionName: ${{ parameters.solutionName }}
            solutionDirectory: ${{ parameters.solutionDirectory }}
            buildConfiguration: ${{ parameters.buildConfiguration }}

        - ${{ if and(ne(contains(variables['Build.SourceBranchName'],'refs/tags/v')), eq(variables['Build.Reason'], 'IndividualCI')) }}:
          - template: ../steps/dotnet-test.yaml
            parameters: 
              solutionName: ${{ parameters.solutionName }}
              solutionDirectory: ${{ parameters.solutionDirectory }}
              buildConfiguration: ${{ parameters.buildConfiguration }}

        - ${{ if and(ne(contains(variables['Build.SourceBranchName'],'refs/tags/v')), eq(variables['Build.Reason'], 'IndividualCI')) }}:
          - template: ../steps/dotnet-sonarcloud-analyze.yaml
        
        

        
              


              
