parameters:
    - name: agentPool
      type: string
    - name: solutionName
      type: string
    - name: solutionDirectory
      type: string
    - name: developmentFrameworkVersion
      type: string
    - name: buildConfiguration
      type: string
    - name: packageDetails
      type: object

stages:
  - stage: Publish
    condition: and(contains(variables['Build.SourceBranch'], 'refs/tags /v'), eq(variables['Build.Reason'], 'IndividualCI'))
    jobs:
      - job: Publis_DotNet_Package_Job
        displayName: Publish .Net Package
        ${{ if ne(parameters.agentPool, 'null')}}:
          pool:
            vmImage: ${{ parameters.agentPool }}
        steps:

        - template: ../steps/dotnet-framework.yaml
          parameters: 
            developmentFrameworkVersion: ${{ parameters.developmentFrameworkVersion }}
               
        - template: ../steps/dotnet-package.yaml
          parameters: 
            solutionName: ${{ parameters.solutionName }}
            solutionDirectory: ${{ parameters.solutionDirectory }}
            buildConfiguration: ${{ parameters.buildConfiguration }}
            packageId: ${{ parameters.packageDetails.packageId }}
            authors: ${{ parameters.packageDetails.authors }}
            company: ${{ parameters.packageDetails.company }}
        
        - template: ../steps/dotnet-publish.yaml
          parameters: 
            packageId: ${{ parameters.packageDetails.packageId }}
            nugetSource: ${{parameters.packageDetails.nugetSource}}   


        



        
              


              
