parameters:
    - name: solutionName
      type: string
    - name: solutionDirectory
      type: object
    - name: buildConfiguration
      type: string

steps:

- task: DotNetCoreCLI@2
  displayName: UnitTest .Net Project
  inputs:
    command: 'test'
    projects: ${{ parameters.solutionDirectory }}/**/*.UnitTests.csproj
    arguments: --configuration ${{ parameters.buildConfiguration }} --collect "Code Coverage"
    testRunTitle: 'Unit Tests'
    publishTestResults: true