parameters:
    - name: solutionName
      type: string
    - name: solutionDirectory
      type: object
    - name: buildConfiguration
      type: string

steps:

- task: DotNetCoreCLI@2
  displayName: UnitTest .Net Project
  inputs:
    command: 'test'
    projects: "${{ parameters.solutionDirectory }}/**/*.UnitTests.csproj"
    testRunTitle: 'Unit Tests'
    arguments: /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=$(Build.SourcesDirectory)/coverage/

- task: Bash@3
  displayName: Move Code Coverage Tests
  inputs:
    targetType: inline
    script: |
      cp $(BUILD_SOURCE)\coverage\coverage.opencover.xml $(AGENT_TEMP)\coverage.opencover.xml
  env: 
    BUILD_SOURCE: $(Build.SourcesDirectory)
    AGENT_TEMP: $(Agent.TempDirectory)
