parameters:
    - name: nugetSource
      type: string
    - name: packageId
      type: string

steps:

- task: PowerShell@2
  displayName: "Publish Nuget Package"
  inputs:
    targetType: inline
    script: |
      dotnet nuget push "$(Build.ArtifactStagingDirectory)/nuget/${{ parameters.packageId }}.$(buildVersionId).nupkg" --api-key $(nugetApiKey) --source ${{ parameters.nugetSource }}
