parameters:
    - name: solutionName
      type: string
    - name: solutionDirectory
      type: object
    - name: buildConfiguration
      type: string

steps:

- task: Bash@3
  displayName: UnitTest .Net Project
  inputs:
    targetType: inline
    script: |
      dotnet test ${SOLUTION_DIRECTORY} /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=${BUILD_SOURCE}/coverage/
  env: 
    BUILD_SOURCE: $(Build.SourcesDirectory)
    SOLUTION_DIRECTORY: ${{ parameters.solutionDirectory }}

- task: Bash@3
  displayName: Move Code Coverage Tests
  inputs:
    targetType: inline
    script: |
      cp ${BUILD_SOURCE} ${AGENT_TEMP}
  env: 
    BUILD_SOURCE: "$(Build.SourcesDirectory)/coverage/coverage.opencover.xml"
    AGENT_TEMP: "$(Agent.TempDirectory)/coverage.opencover.xml"
