parameters:
    - name: organization
      type: string
    - name: projectKey
      type: string
    - name: projectName
      type: string
    - name: serviceConnection
      type: string

steps:

- task: SonarCloudPrepare@1
  displayName: Configure SonarCloud Project
  inputs:
    SonarCloud: ${{ parameters.serviceConnection }}
    organization: ${{ parameters.organization }}
    scannerMode: 'MSBuild'
    projectKey: ${{ parameters.projectKey }}
    projectName: ${{ parameters.projectName }}
    extraProperties: |
      sonar.exclusions="/bin//,/obj//,/Migrations/,/*.dll"
      sonar.coverage.exclusions="test/"
      sonar.verbose=true