parameters:
    - name: buildConfiguration
      type: string
    - name: solutionDirectory
      type: string
    - name: solutionName
      type: string
    - name: nugetSource
      type: string
    - name: packageId
      type: string

steps:

- task: PowerShell@2
  displayName: "Publish Nuget Package"
  inputs:
    targetType: inline
    script: |
      Set-Location -Path "$(Build.StagingDirectory)/packages"
      ls

- task: PowerShell@2
  displayName: "Publish Nuget Package"
  inputs:
    targetType: inline
    script: |
      dotnet nuget push "$(Build.StagingDirectory)/packages/${{ parameters.solutionName }}.$(buildVersionId).nupkg" --api-key $(nugetApiKey) --source ${{ parameters.nugetSource }}