parameters:
    - name: solutionDirectory
      type: string
    - name: buildConfiguration
      type: string

steps:
  
- task: DotNetCoreCLI@2
  displayName: Publish Code Coverage
  inputs:
    command: 'test'
    projects: "${{ parameters.solutionDirectory }}/**/*.UnitTests.csproj"
    testRunTitle: 'Unit Tests - Publish Coverage'
    arguments: '--configuration ${{ parameters.buildConfiguration }} --collect "Code coverage'
    publishTestResults: true
