name: $(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - trunk
    - feature/*
  tags:
    include:
    - v*

pr:
  branches:
    include:
    - trunk

variables:
- group: global-secrets

extends:
  template: ../types/cicd-libraries.yaml
  parameters:
    solutionType:  dotnet #
    agentPool: 'windows-latest'
    settings:
      solutionName:  Example.Solution #
      solutionDirectory: src/sharedlibraries/nuget/Example.Solution 
      developmentFrameworkVersion: 6.0.x #
      buildConfiguration: Release
      sonarcloud:
        serviceConnection: sonarcloud_sleedigital_platform_services_devops
        organization: sowens81
        projectKey: sowens81_SleeDigital_Platform_Services_DevOps
        projectName: SleeDigital_Platform_Services_DevOps
      packageDetails:
        nugetSource: https://api.nuget.org/v3/index.json
        packageId: SleeDigital.Example.Solution
        authors: Steve Owens
        company: Slee Digital

