parameters:
    - name: solutionType
      type: string
    - name: agentPool
      type: string
    - name: settings
      type: object

stages:
  - ${{ if eq(parameters['solutionType'], 'dotnet' ) }}:
    - template: ../stages/build-dotnet-packages.yaml
      parameters:
        agentPool: ${{ parameters.agentPool }}
        solutionName: ${{ parameters.settings.solutionName }}
        solutionDirectory: ${{ parameters.settings.solutionDirectory }}
        developmentFrameworkVersion: ${{ parameters.settings.developmentFrameworkVersion }}
        buildConfiguration: ${{ parameters.settings.buildConfiguration }}
        sonarcloud: ${{ parameters.settings.sonarcloud }}
  
  - ${{ if eq(parameters['solutionType'], 'dotnet' ) }}:
    - template: ../stages/publish-dotnet-packages.yaml
      parameters:
        agentPool: ${{ parameters.agentPool }}
        solutionName: ${{ parameters.settings.solutionName }}
        solutionDirectory: ${{ parameters.settings.solutionDirectory }}
        developmentFrameworkVersion: ${{ parameters.settings.developmentFrameworkVersion }}
        buildConfiguration: ${{ parameters.settings.buildConfiguration }}
        packageDetails: ${{ parameters.settings.packageDetails }}